config/routes.rb
Rails.application.routes.draw do
  resources :users
  namespace :admin do
    resources :documents
    resources :users

    root to: "documents#index"
  end

  namespace :public do
    get 'documents/:id', to: "documents#show", as: :document
    get 'health_checks', to: "health_checks#index"
  end

  resources :documents
  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }

  root "home#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {
    teacher: "teacher",
    student: "student"
  }

  belongs_to :creator, class_name: :User, optional: true
  has_many :students, class_name: :User, foreign_key: :creator_id
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    authorize User
    @users = policy_scope(User)
  end

  # GET /users/1 or /users/1.json
  def show
    authorize @user
  end

  # GET /users/new
  def new
    @user = User.new
    authorize @user
  end

  # GET /users/1/edit
  def edit
    authorize @user
  end

  # POST /users or /users.json
  def create
    authorize User
    @user = User.new(user_params.merge(creator: current_user, role: User.roles["student"]))

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    authorize @user
    respond_to do |format|
      if @user.update(user_params.merge(creator: current_user))
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    authorize @user
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :password %>
    <%= form.password_field :password, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-ultramarine-blue-400 hover:brightness-110 text-seafoam-400 underline inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/users/_navigation.html.erb
  <div class="flex gap-4">
    <% if action_name != "show" && policy(user).show? %>
      <%= link_to user, class: "w-6 h-fit", title: "Show User" do  %>
        <%= heroicon "eye" %>
      <% end %>
    <% end %>

    <% if action_name != "edit" && policy(user).edit? %>
      <%= link_to edit_user_path(user), class: "w-6 h-fit", title: "Edit User" do  %>
        <%= heroicon "pencil" %>
      <% end %>
    <% end %>

    <% if policy(user).destroy? %>
      <%= link_to user_path(user), class: "w-6 h-fit", title: "Delete User", data: { turbo_method: :delete, turbo_confirm: t("confirmations.are_you_sure") } do  %>
        <%= heroicon "trash" %>
      <% end %>
    <% end %>
  </div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class="pt-2">
  <div class="flex justify-between items-center">
    <div class="flex-1">
      <div class="flex gap-2">
        <strong class="block mb-1">Email:</strong>
        <p><%= user.email %></p>
      </div>
    </div>

    <%= render partial: "navigation", locals: { user: } %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= link_to "<< Back", users_path, class: "block mb-2" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Editing user</h1>

    <%= render partial: "navigation", locals: { user: @user } %>
  </div>

  <%= render "form", user: @user %>
</div>

app/views/users/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center mb-2">
    <h1 class="font-bold text-4xl">Students</h1>

    <% if policy(User).new? %>
      <%= link_to "New user", new_user_path, class: "rounded-lg py-3 px-5 bg-ultramarine-blue-400 hover:brightness-110 text-white block font-medium" %>
    <% end %>
  </div>

  <div id="users" class="min-w-full divide-y gap-2 flex flex-col">
    <% if @users.exists? %>
      <%= render @users %>
    <% else %>
      <div class="border-gray-200 border rounded-md p-10">
        <div class="flex flex-col gap-4 items-center">
          <p><%= t(".empty.description") %></p>
          <%= link_to "New user", new_user_path, class: "rounded-lg py-3 px-5 bg-ultramarine-blue-400 hover:brightness-110 text-white block font-medium w-fit" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= link_to "<< Back", users_path, class: "block mb-2" %>

  <h1 class="font-bold text-4xl">New user</h1>

  <%= render "form", user: @user %>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= link_to "<< Back", users_path, class: "block mb-2" %>
    <%= render @user %>
  </div>
</div>