config/routes.rb
Rails.application.routes.draw do
  resources :users
  namespace :admin do
    resources :documents
    resources :users

    root to: "documents#index"
  end

  namespace :public do
    get 'documents/:id', to: "documents#show", as: :document
    get 'health_checks', to: "health_checks#index"
  end

  resources :documents
  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }

  root "home#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/document.rb
class Document < ApplicationRecord
  has_one_attached :file
  belongs_to :uploader, class_name: :User

  validates :file, presence: true
end

app/controllers/admin/documents_controller.rb
module Admin
  class DocumentsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]

  # GET /documents or /documents.json
  def index
    authorize Document

    @documents = policy_scope(Document)
  end

  # GET /documents/1 or /documents/1.json
  def show
    authorize @document
  end

  # GET /documents/new
  def new
    @document = Document.new
    authorize @document
  end

  # GET /documents/1/edit
  def edit
    authorize @document
  end

  # POST /documents or /documents.json
  def create
    authorize Document
    @document = Document.new(document_params.merge(uploader: current_user))

    respond_to do |format|
      if @document.save
        format.html { redirect_to document_url(@document), notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    authorize @document

    respond_to do |format|
      if @document.update(document_params.merge(uploader: current_user))
        format.html { redirect_to document_url(@document), notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    authorize @document
    @document.destroy!

    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:name, :file)
    end
end

app/views/documents/_document.html.erb
<div id="<%= dom_id document %>">
  <div class="flex justify-between items-center">
    <div class="flex-1">
      <div class="flex gap-2">
        <strong class="block mb-1">Name:</strong>
        <p><%= document.name %></p>
      </div>

      <% if document.uploader.present? %>
        <div class="flex gap-2">
          <strong class="block mb-1">Teacher:</strong>
          <p><%= document.uploader.email %></p>
        </div>
      <% end %>

      <div class="flex gap-2">
        <strong class="block mb-1">File:</strong>
        <% if document.file.attached? %>
          <%= link_to document.file.filename, document.file %>
        <% end %>
      </div>
    </div>

    <%= render partial: "navigation", locals: { document: } %>
  </div>

  <% if document.file.attached? && action_name == "show" %>
    <div class="p-4 border-gray-300 border rounded-md">
      <%= render FilePreviewComponent.new(document:) %>
    </div>
  <% end %>
</div>

app/views/documents/_form.html.erb
<%= form_with(model: document, class: "contents") do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :file %>
    <%= form.file_field :file, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-ultramarine-blue-400 hover:brightness-110 text-seafoam-400 underline inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/documents/_navigation.html.erb
<div class="flex gap-4">
  <div data-controller="clipboard" data-clipboard-success-content-value="Copied!" class="flex gap-2">
    <span data-clipboard-target="button" class="text-green-500"></span>
    <span class="hidden">
      <input type="text" value="<%= public_document_url(document.uuid) %>" data-clipboard-target="source" />
    </span>

    <button title="Copy Public URL" type="button" data-action="clipboard#copy" class="w-6 h-fit p-0 border-0">
      <span class="block w-6 h-fit text-seafoam-400">
        <%= heroicon "clipboard" %>
      </span>
    </button>
  </div>

  <% if action_name != "show" && policy(document).show? %>
    <%= link_to document, class: "w-6 h-fit", title: "Show Document" do  %>
      <%= heroicon "eye" %>
    <% end %>
  <% end %>

  <% if action_name != "edit" && policy(document).edit? %>
    <%= link_to edit_document_path(document), class: "w-6 h-fit", title: "Edit Document" do  %>
      <%= heroicon "pencil" %>
    <% end %>
  <% end %>

  <% if policy(document).destroy? %>
    <%= link_to document_path(document), class: "w-6 h-fit", title: "Delete Document", data: { turbo_method: :delete, turbo_confirm: t("confirmations.are_you_sure") } do  %>
      <%= heroicon "trash" %>
    <% end %>
  <% end %>
</div>

app/views/documents/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= link_to "<< Back", documents_path, class: "block mb-2" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Editing document</h1>

    <%= render partial: "navigation", locals: { document: @document } %>
  </div>

  <%= render "form", document: @document %>
</div>

app/views/documents/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center mb-2">
    <h1 class="font-bold text-4xl">Documents</h1>

    <% if policy(Document).new? %>
      <%= link_to "New document", new_document_path, class: "rounded-lg py-3 px-5 bg-ultramarine-blue-400 hover:brightness-110 text-white block font-medium" %>
    <% end %>
  </div>

  <div id="documents" class="min-w-full divide-y gap-2 flex flex-col">
    <% if @documents.exists? %>
      <%= render @documents %>
    <% else %>
      <div class="border-gray-200 border rounded-md p-10">
        <div class="flex flex-col gap-4 items-center">
          <p><%= t(".empty.description") %></p>
          <%= link_to "New document", new_document_path, class: "rounded-lg py-3 px-5 bg-ultramarine-blue-400 hover:brightness-110 text-white block font-medium w-fit" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/documents/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= link_to "<< Back", documents_path, class: "block mb-2" %>

  <h1 class="font-bold text-4xl">New document</h1>

  <%= render "form", document: @document %>
</div>

app/views/documents/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= link_to "<< Back", documents_path, class: "block mb-2" %>
    <%= render @document %>
  </div>
</div>